### ISSUE TITLE
LSMS.cpp:94:23: error

### ISSUE THREAD

**Issue by pdkn** [Seeed-Studio/Arduino_IDE_for_RePhone#10]
I was getting this error: LSMS.cpp:94:23: error: no 'int LSMSClass::endSMS()' member function declared in class 'LSMSClass'

Editing LGMS.h with below fixed issue:

// DESCRIPTION
//  ends an SMS
// RETURNS
//  1: Succeed, 0: Fail
int endSMS();

**Comment by WayenWeng** [comment]
Thanks for fix the error of SMS.
