### ISSUE TITLE
Arduino Example for TCP socket

### ISSUE THREAD

**Issue by heri16** [Seeed-Studio/Arduino_IDE_for_RePhone#3]
Please add an ino example file for opening tcp socket to an IP address and port.

**Comment by WayenWeng** [comment]
Hi,
There is add a library about BSD TCP Client. You can make reference to ..\Arduino_IDE_for_RePhone\hardware\arduino\mtk\libraries\Network_BSD_TCPClient.
https://github.com/Seeed-Studio/Arduino_IDE_for_RePhone/tree/master/hardware/arduino/mtk/libraries/Network_BSD_TCPClient
