### ISSUE TITLE
LBTClient

### ISSUE THREAD

**Issue by durvesh09** [Seeed-Studio/Arduino_IDE_for_RePhone#6]
Hi,

   I m unable to send data from xadow rephone to android phone using LBTClient/LBTServer library.
It has function "write_size = LBTClient.write((uint8_t*)"LinkIt BT Client", 16); " , but there is nothing received on my phone. I m able to send data from my android phone to xadow but facing problem in vice versa

**Comment by WayenWeng** [comment]
Hi,
I test the BT SPP send/receive and it is ok.
I have already sent my test code to your mail, please test it again.
