### ISSUE TITLE
"pin = pin - A1" is executed twice in attachinterrupt and detachInterrupt

### ISSUE THREAD

**Issue by ksathara** [Seeed-Studio/Arduino_IDE_for_RePhone#8]
pin = pin - A1;  appears in both attachInterrupt and detachInterrupt functions. Since attachInterrupt calls detachInterrupt after "pin = pin - A1" statement, it gets deducted twice.

**Comment by WayenWeng** [comment]
Hi, thank for your message. I have already fix the bug.
